Support OneUI 6
ris58h/galaxyfinder-widget pull request #5
Opened 2023-11-19 15:05 UTC by Re-Tails

Use OneUI Home's intent when Android 14 or higher.
Finder doesn't seem to work as it did on OneUI 5 anymore. It's still installed but activities/intents seem to have changed.

Fixes #4

2023-11-19 15:27 UTC, Re-Tails commented
Screen recording on OneUI 6
https://github.com/ris58h/galaxyfinder-widget/assets/25842958/ef47fa32-b9ce-44a5-b8f9-8c97f40ee823

2023-11-21 04:02 UTC, ris58h requested changes

2023-11-21 04:02 UTC, ris58h commented on app/src/main/kotlin/ris58h/galaxyfinder/widget/FinderWidget.kt
> +        else {
There shouldn't be a new line according to the formatting rules.

2023-11-21 13:31 UTC, ris58h approved these changes

2023-11-21 13:31 UTC, merged